"""
OpenCode SDK Client Wrapper for 7000%AUTO
Uses OpenCode SDK (opencode-ai) for AI agent interactions.
"""

import asyncio
import json
import logging
from pathlib import Path
from typing import Optional, Dict, Any, AsyncIterator, List

import httpx

from config import settings

logger = logging.getLogger(__name__)

# Agent system prompts cache
_AGENT_PROMPTS: Dict[str, str] = {}

# OpenCode configuration cache
_OPENCODE_CONFIG: Optional[Dict[str, Any]] = None

# Pre-compiled regex patterns for performance
_FRONTMATTER_PATTERN = re.compile(r'^---\s*\n.*?\n---\s*\n', re.DOTALL)
_VALID_AGENT_NAME_PATTERN = re.compile(r'^[a-zA-Z0-9_-]+$')


def _load_opencode_config() -> Dict[str, Any]:
    """Load opencode.json configuration"""
    global _OPENCODE_CONFIG
    if _OPENCODE_CONFIG is not None:
        return _OPENCODE_CONFIG
    
    config_path = Path("opencode.json")
    if config_path.exists():
        try:
            _OPENCODE_CONFIG = json.loads(config_path.read_text(encoding="utf-8"))
            return _OPENCODE_CONFIG
        except Exception as e:
            logger.warning(f"Failed to load opencode.json: {e}")
    
    # Fallback configuration - should normally be generated by main.py
    # If we reach here without proper config, something is wrong
    if not settings.OPENCODE_SDK or not settings.OPENCODE_MODEL:
        logger.error("OpenCode settings not configured. Set OPENCODE_SDK, OPENCODE_MODEL, etc.")
        raise RuntimeError("Missing required OpenCode environment variables")
    
    # Derive provider name from SDK package (e.g. @ai-sdk/anthropic -> anthropic)
    sdk_parts = settings.OPENCODE_SDK.split("/")
    provider_name = sdk_parts[-1]
    
    _OPENCODE_CONFIG = {
        "provider": {
            provider_name: {
                "npm": settings.OPENCODE_SDK,
                "name": provider_name.title(),
                "options": {
                    "baseURL": settings.OPENCODE_API_BASE,
                    "apiKey": "{env:OPENCODE_API_KEY}"
                },
                "models": {
                    settings.OPENCODE_MODEL: {
                        "name": settings.OPENCODE_MODEL,
                        "options": {
                            "max_tokens": settings.OPENCODE_MAX_TOKENS
                        }
                    }
                }
            }
        },
        "model": f"{provider_name}/{settings.OPENCODE_MODEL}"
    }
    return _OPENCODE_CONFIG


def _remove_yaml_frontmatter(content: str) -> str:
    """Remove YAML frontmatter (---...---) from markdown content"""
    return _FRONTMATTER_PATTERN.sub('', content).strip()


def _load_agent_prompt(agent_name: str) -> str:
    """Load agent system prompt from .opencode/agent/{agent_name}.md"""
    if agent_name in _AGENT_PROMPTS:
        return _AGENT_PROMPTS[agent_name]
    
    # Validate agent name to prevent path traversal
    if not _VALID_AGENT_NAME_PATTERN.match(agent_name):
        logger.warning(f"Invalid agent name format: {agent_name}")
        fallback = f"You are {agent_name}, an AI assistant. Complete the task given to you."
        _AGENT_PROMPTS[agent_name] = fallback
        return fallback
    
    agent_path = Path(f".opencode/agent/{agent_name}.md")
    if agent_path.exists():
        content = agent_path.read_text(encoding="utf-8")
        # Remove YAML frontmatter if present
        content = _remove_yaml_frontmatter(content)
        _AGENT_PROMPTS[agent_name] = content
        return content
    
    # Fallback generic prompt
    fallback = f"You are {agent_name}, an AI assistant. Complete the task given to you."
    _AGENT_PROMPTS[agent_name] = fallback
    return fallback


class OpenCodeError(Exception):
    """Base exception for OpenCode client errors"""
    pass


def _safe_get(obj: Any, key: str, default: Any = None) -> Any:
    """Get a value from either a dict or an object attribute."""
    if obj is None:
        return default
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


class OpenCodeClient:
    """
    Client for AI agent interactions using OpenCode SDK.
    
    This client wraps the opencode-ai SDK to provide session management
    and message handling for the 7000%AUTO agent pipeline.
    
    Agents are specified via the 'mode' parameter in session.chat(),
    which corresponds to agents defined in opencode.json under the 'agent' key.
    The 'system' parameter provides a fallback prompt from .opencode/agent/*.md files.
    Each agent in opencode.json has its own model, prompt, tools, and permissions.
    """
    
    def __init__(self, base_url: Optional[str] = None):
        self.base_url = base_url or settings.OPENCODE_SERVER_URL
        self._client: Optional[Any] = None
        self._sessions: Dict[str, Dict[str, Any]] = {}
        
        # Load configuration from opencode.json
        config = _load_opencode_config()
        
        # Derive provider from SDK package name (e.g. @ai-sdk/anthropic -> anthropic)
        # This matches the provider key generated in main.py's generate_opencode_config()
        if not settings.OPENCODE_SDK or not settings.OPENCODE_MODEL:
            raise RuntimeError("Missing required OpenCode environment variables (OPENCODE_SDK, OPENCODE_MODEL)")
        
        sdk_parts = settings.OPENCODE_SDK.split("/")
        self.provider_id = sdk_parts[-1]
        self.model_id = settings.OPENCODE_MODEL
        
        logger.info(f"OpenCode client using provider={self.provider_id}, model={self.model_id}")
    
    async def _get_client(self):
        """Get or create AsyncOpencode client"""
        if self._client is None:
            try:
                from opencode_ai import AsyncOpencode
                
                # Set generous timeout for AI model responses (300 seconds)
                # AI models can take a long time to generate responses
                timeout = httpx.Timeout(300.0, connect=30.0)
                
                client_kwargs = {
                    "timeout": timeout,
                }
                if self.base_url:
                    client_kwargs["base_url"] = self.base_url
                
                self._client = AsyncOpencode(**client_kwargs)
                logger.info(f"OpenCode client initialized (base_url: {self.base_url or 'default'}, timeout: 300s)")
            except ImportError:
                raise OpenCodeError("opencode-ai package not installed. Run: pip install opencode-ai")
            except Exception as e:
                raise OpenCodeError(f"Failed to initialize OpenCode client: {e}")
        
        return self._client
    
    async def _close_client(self):
        """Close the OpenCode client"""
        if self._client is not None:
            try:
                await self._client.close()
            except Exception as e:
                logger.warning(f"Error closing OpenCode client: {e}")
            finally:
                self._client = None
    
    async def create_session(self, agent_name: str) -> str:
        """
        Create a new session for an agent.
        
        Args:
            agent_name: Name of the agent (e.g., "ideator", "planner")
            
        Returns:
            Session ID string
        """
        try:
            client = await self._get_client()
            
            # Create session via OpenCode SDK
            # Pass extra_body={} to send empty JSON body (server expects JSON even if empty)
            session = await client.session.create(extra_body={})
            session_id = session.id
            
            # Store session metadata including agent name and prompt
            system_prompt = _load_agent_prompt(agent_name)
            self._sessions[session_id] = {
                "agent": agent_name,
                "system_prompt": system_prompt,
                "opencode_session": session,
            }
            
            logger.info(f"Created session {session_id} for agent {agent_name}")
            return session_id
            
        except OpenCodeError:
            raise
        except Exception as e:
            server_url = self.base_url or "default"
            logger.error(f"Failed to create session for agent {agent_name}: {e}")
            raise OpenCodeError(
                f"Failed to create session (is OpenCode server running at {server_url}?): {e}"
            )
    
    async def send_message(self, session_id: str, message: str, timeout_seconds: int = 120) -> Dict[str, Any]:
        """
        Send a message and get response from OpenCode.
        
        Args:
            session_id: Session ID from create_session
            message: User message to send
            timeout_seconds: Maximum time to wait for agent completion (default 120s)
            
        Returns:
            Dict with "content" (raw response) and "parsed" (extracted JSON)
        """
        if session_id not in self._sessions:
            raise OpenCodeError(f"Session {session_id} not found")
        
        session_data = self._sessions[session_id]
        agent_name = session_data["agent"]
        
        try:
            client = await self._get_client()
            
            logger.info(f"Sending message to session {session_id} (agent: {agent_name})")
            
            # Build message parts
            parts: List[Dict[str, Any]] = [
                {"type": "text", "text": message}
            ]
            
            # Enable all MCP tools for the agent
            # This allows agents to use search, github, x_api, database tools
            tools: Dict[str, bool] = {"*": True}
            
            # Send chat message via OpenCode SDK
            # - mode: specifies agent/mode to use (maps to agents in opencode.json)
            # - system: provides fallback system prompt if mode isn't recognized
            # - tools: enables MCP server tools defined in opencode.json
            # - max_tokens is configured in opencode.json model options
            # OpenCode server loads agent config from opencode.json based on mode
            response = await client.session.chat(
                session_id,
                model_id=self.model_id,
                provider_id=self.provider_id,
                parts=parts,
                mode=agent_name,  # Specify agent mode from opencode.json
                system=session_data["system_prompt"],  # Fallback system prompt
                tools=tools,
            )
            
            # Check for errors in the response
            if hasattr(response, 'error') and response.error:
                error_msg = str(response.error)
                logger.error(f"OpenCode response error: {error_msg}")
                raise OpenCodeError(f"Agent error: {error_msg}")
            
            # session.chat() returns immediately - agent may still be running
            # Check if response is complete by looking at time.completed
            # If not complete, poll until agent finishes
            await self._wait_for_completion(client, session_id, response, timeout_seconds)
            
            # Now fetch the actual message content
            content = await self._fetch_message_content(client, session_id)
            
            logger.info(f"Received response for session {session_id} ({len(content)} chars)")
            
            return {"content": content}
            
        except OpenCodeError:
            raise
        except Exception as e:
            server_url = self.base_url or "default"
            logger.error(f"Failed to send message to session {session_id}: {e}")
            raise OpenCodeError(
                f"Failed to send message (is OpenCode server running at {server_url}?): {e}"
            )
    
    def _is_message_completed(self, info: Any, context: str = "") -> bool:
        """
        Check if a message is completed using multiple strategies.
        Handles both dict and object info representations.
        
        Checks in order:
        1. time.completed is not None (primary - matches actual API response)
        2. status == "completed"
        3. completed_at timestamp exists
        
        Args:
            info: Message info object or dict
            context: Context string for debug logging
            
        Returns:
            True if message is completed, False otherwise
        """
        if info is None:
            return False
        
        # Debug log: dump available fields
        if logger.isEnabledFor(logging.DEBUG):
            info_fields = {}
            for attr in ['id', 'role', 'status', 'completed_at', 'created_at', 'time', 'error', 'finish']:
                info_fields[attr] = _safe_get(info, attr, '<not found>')
            logger.debug(f"{context} - info fields: {info_fields}")
        
        # Strategy 1: Check time.completed (primary - matches actual API response)
        time_info = _safe_get(info, 'time')
        if time_info:
            completed = _safe_get(time_info, 'completed')
            if completed is not None:
                logger.debug(f"{context} - time.completed={completed}")
                return True
        
        # Strategy 2: Check finish field (e.g. finish='stop' means done)
        finish = _safe_get(info, 'finish')
        if finish == 'stop':
            logger.debug(f"{context} - finish={finish}")
            return True
        
        # Strategy 3: Check status field
        status = _safe_get(info, 'status')
        if status is not None:
            logger.debug(f"{context} - status={status}")
            if status == "completed":
                return True
            if status in ("in_progress", "incomplete"):
                return False
        
        # Strategy 4: Check completed_at timestamp
        completed_at = _safe_get(info, 'completed_at')
        if completed_at is not None:
            logger.debug(f"{context} - completed_at={completed_at}")
            return True
        
        return False

    async def _wait_for_completion(
        self, 
        client: Any, 
        session_id: str, 
        initial_response: Any,
        timeout_seconds: int
    ) -> None:
        """
        Wait for agent to complete processing.
        
        The session.chat() method returns immediately with an AssistantMessage.
        We need to poll session.messages() until the message is complete.
        
        Completion is determined by:
        1. status == "completed"
        2. completed_at timestamp exists
        3. time.completed exists (legacy fallback)
        
        Args:
            client: OpenCode client instance
            session_id: Session ID
            initial_response: Initial AssistantMessage from session.chat()
            timeout_seconds: Maximum time to wait for completion
        """
        # Extract message info - could be nested under .info (dict or object)
        initial_info = _safe_get(initial_response, 'info', initial_response)
        
        # Get the message ID from info (where the real data lives)
        message_id = _safe_get(initial_info, 'id') or _safe_get(initial_response, 'id')
        
        # Check for error in initial response
        self._check_response_for_error(initial_response, "initial response")
        
        # Debug log initial response structure
        if logger.isEnabledFor(logging.DEBUG):
            logger.debug(f"Session {session_id}: Initial response type={type(initial_response).__name__}")
            if hasattr(initial_response, 'model_dump'):
                try:
                    dump = initial_response.model_dump()
                    logger.debug(f"Session {session_id}: Initial response dump={dump}")
                except Exception:
                    pass
        
        # Check if initial response is already complete
        if self._is_message_completed(initial_info, f"Session {session_id} initial"):
            logger.info(f"Session {session_id}: Agent already completed in initial response (message: {message_id})")
            return
        
        # Poll for completion
        poll_interval = 1.0  # seconds
        max_polls = int(timeout_seconds / poll_interval)
        
        logger.info(f"Session {session_id}: Agent still running (message: {message_id}), polling for completion...")
        
        for poll_count in range(max_polls):
            await asyncio.sleep(poll_interval)
            
            try:
                # Fetch messages to check completion status
                messages_response = await client.session.messages(session_id)
                
                if not messages_response:
                    logger.debug(f"Session {session_id}: No messages in response (poll {poll_count + 1})")
                    continue
                
                # Find the specific message by ID, or fall back to last assistant message
                target_message = None
                
                for msg in reversed(messages_response):
                    info = _safe_get(msg, 'info')
                    if not info:
                        continue
                    
                    # Match by message ID if available
                    if message_id:
                        msg_id = _safe_get(info, 'id')
                        if msg_id == message_id:
                            target_message = msg
                            break
                    else:
                        # Fallback: match last assistant message
                        role = _safe_get(info, 'role')
                        if role == 'assistant':
                            target_message = msg
                            break
                
                if target_message:
                    info = _safe_get(target_message, 'info')
                    if info:
                        # Check for errors in the message
                        self._check_response_for_error(info, f"message {message_id}")
                        
                        # Check completion using multiple strategies
                        context = f"Session {session_id} poll {poll_count + 1}"
                        if self._is_message_completed(info, context):
                            logger.info(f"Session {session_id}: Agent completed after {poll_count + 1}s (message: {message_id})")
                            return
                else:
                    logger.debug(f"Session {session_id}: No matching assistant message found (poll {poll_count + 1})")
                
                # Log progress every 10 polls
                if (poll_count + 1) % 10 == 0:
                    logger.info(f"Session {session_id}: Still waiting... ({poll_count + 1}s elapsed)")
                    
            except OpenCodeError:
                raise
            except Exception as e:
                logger.warning(f"Session {session_id}: Error polling for completion: {e}")
        
        # Timeout reached
        logger.warning(f"Session {session_id}: Timeout after {timeout_seconds}s waiting for agent completion")
        raise OpenCodeError(f"Agent timed out after {timeout_seconds} seconds")
    
    def _check_response_for_error(self, response: Any, context: str = "") -> None:
        """
        Check response object for error information and raise OpenCodeError if found.
        
        Args:
            response: Response object to check (could be message info or full response)
            context: Context string for error messages
            
        Raises:
            OpenCodeError: If an error is detected in the response
        """
        if response is None:
            return
        
        # Check for 'error' attribute directly (handles both dict and object)
        error = _safe_get(response, 'error')
        if error:
            error_message = self._extract_error_message(error)
            if error_message:
                logger.error(f"API error detected in {context}: {error_message}")
                raise OpenCodeError(f"API Error: {error_message}")
        
        # Check via model_dump if available
        if hasattr(response, 'model_dump'):
            try:
                dump = response.model_dump()
                if isinstance(dump, dict) and 'error' in dump and dump['error']:
                    error_data = dump['error']
                    error_message = self._extract_error_message_from_dict(error_data)
                    if error_message:
                        logger.error(f"API error detected in {context} (from dump): {error_message}")
                        raise OpenCodeError(f"API Error: {error_message}")
            except Exception as e:
                logger.debug(f"Could not check model_dump for errors: {e}")
    
    def _extract_error_message(self, error: Any) -> Optional[str]:
        """
        Extract a human-readable error message from an error object or dict.
        
        Args:
            error: Error object or dict (could be ProviderAuthError, APIError, etc.)
            
        Returns:
            Error message string or None
        """
        if error is None:
            return None
        
        if isinstance(error, dict):
            return self._extract_error_message_from_dict(error)
        
        # Try to get error name/type
        error_name = getattr(error, 'name', None) or type(error).__name__
        
        # Try to get data.message or data.error
        data = _safe_get(error, 'data')
        if data:
            message = _safe_get(data, 'message') or _safe_get(data, 'error')
            if message:
                return f"{error_name}: {message}"
        
        # Try direct message attribute
        message = _safe_get(error, 'message')
        if message:
            return f"{error_name}: {message}"
        
        # Check for common auth error patterns
        if 'Auth' in error_name or 'auth' in str(error).lower():
            return f"{error_name}: Authentication failed - check your OPENCODE_API_KEY"
        
        # Fallback to string representation
        error_str = str(error)
        if error_str and error_str != str(type(error)):
            if len(error_str) > 200:
                error_str = error_str[:200] + "..."
            return f"{error_name}: {error_str}"
        
        return error_name
    
    def _extract_error_message_from_dict(self, error_data: Any) -> Optional[str]:
        """
        Extract error message from a dict representation of an error.
        
        Args:
            error_data: Error data as dict
            
        Returns:
            Error message string or None
        """
        if not isinstance(error_data, dict):
            return str(error_data) if error_data else None
        
        error_name = error_data.get('name', 'Error')
        
        # Check for nested data
        data = error_data.get('data', {})
        if isinstance(data, dict):
            message = data.get('message') or data.get('error')
            if message:
                return f"{error_name}: {message}"
        
        # Direct message
        message = error_data.get('message') or error_data.get('error')
        if message:
            return f"{error_name}: {message}"
        
        # Check for auth errors
        if 'Auth' in error_name or 'ProviderAuth' in error_name:
            return f"{error_name}: Authentication failed - check your OPENCODE_API_KEY"
        
        return error_name if error_name != 'Error' else None

    async def _fetch_message_content(self, client: Any, session_id: str) -> str:
        """
        Fetch actual message content from session messages.
        
        The session.chat() method returns AssistantMessage which only contains metadata.
        To get actual text content, we need to call session.messages() and extract
        TextPart content from the last assistant message.
        
        Args:
            client: OpenCode client instance
            session_id: Session ID
            
        Returns:
            Extracted text content from the last assistant message
            
        Raises:
            OpenCodeError: If an API error is detected in the message
        """
        try:
            # Fetch all messages for the session
            messages_response = await client.session.messages(session_id)
            
            if not messages_response:
                logger.warning(f"No messages found for session {session_id}")
                return ""
            
            # Find the last assistant message
            last_assistant_message = None
            for msg in messages_response:
                info = _safe_get(msg, 'info')
                if info and _safe_get(info, 'role') == 'assistant':
                    last_assistant_message = msg
            
            if not last_assistant_message:
                logger.warning(f"No assistant message found for session {session_id}")
                return ""
            
            # Check for errors
            info = _safe_get(last_assistant_message, 'info')
            if info:
                self._check_response_for_error(info, f"session {session_id}")
            
            # Extract text from parts
            texts = []
            parts = _safe_get(last_assistant_message, 'parts') or []
            for part in parts:
                if _safe_get(part, 'type') == 'text':
                    text = _safe_get(part, 'text', '')
                    if text:
                        texts.append(text)
            
            if texts:
                return '\n'.join(texts)
            
            # Fallback: try to extract from dict representation
            if hasattr(last_assistant_message, 'model_dump'):
                dump = last_assistant_message.model_dump()
                parts_data = dump.get('parts', [])
                for part_data in parts_data:
                    if isinstance(part_data, dict) and part_data.get('type') == 'text':
                        text = part_data.get('text', '')
                        if text:
                            texts.append(text)
                if texts:
                    return '\n'.join(texts)
            
            logger.warning(f"Session {session_id}: No text content found in assistant message")
            return ""
            
        except OpenCodeError:
            raise
        except Exception as e:
            logger.warning(f"Failed to fetch message content: {e}")
            return ""
    
    def _extract_response_content(self, response: Any) -> str:
        """
        Extract text content from OpenCode AssistantMessage response.
        
        The response structure may vary, so we try multiple approaches.
        Based on SDK investigation, AssistantMessage has:
        - id, cost, mode, api_model_id, path, provider_id, role, session_id,
          system, time, tokens, error, summary
        - The text content is typically in path.parts
        """
        # First, check path.parts which is the primary location for content
        if hasattr(response, 'path'):
            path = response.path
            if hasattr(path, 'parts'):
                content = self._extract_parts_content(path.parts)
                if content:
                    logger.debug("Extracted content from response.path.parts")
                    return content
        
        # Try direct parts attribute
        if hasattr(response, 'parts'):
            parts = response.parts
            if isinstance(parts, list):
                texts = []
                for part in parts:
                    if isinstance(part, dict) and part.get('type') == 'text':
                        texts.append(part.get('text', ''))
                    elif hasattr(part, 'text'):
                        texts.append(str(part.text))
                if texts:
                    logger.debug("Extracted content from response.parts")
                    return '\n'.join(texts)
        
        # Try content attribute
        if hasattr(response, 'content'):
            content = response.content
            if content:
                logger.debug("Extracted content from response.content")
                return str(content)
        
        # Try text attribute
        if hasattr(response, 'text'):
            text = response.text
            if text:
                logger.debug("Extracted content from response.text")
                return str(text)
        
        # Fallback: convert response to string via model_dump
        if hasattr(response, 'model_dump'):
            logger.debug("Falling back to model_dump for content extraction")
            dump = response.model_dump()
            # Try to extract text from the dumped structure
            # Add null check for dump['path'] to prevent NoneType error
            if 'path' in dump and dump['path'] is not None and 'parts' in dump['path']:
                parts = dump['path']['parts']
                if parts:
                    texts = [p.get('text', '') for p in parts if p.get('type') == 'text']
                    if texts:
                        return '\n'.join(texts)
            return json.dumps(dump, indent=2)
        
        logger.warning("Could not extract structured content, using str()")
        return str(response)
    
    def _extract_parts_content(self, parts: Any) -> str:
        """Extract text content from message parts"""
        if not parts:
            return ""
        
        texts = []
        for part in parts:
            if isinstance(part, dict):
                if part.get('type') == 'text':
                    texts.append(part.get('text', ''))
            elif hasattr(part, 'text'):
                texts.append(str(part.text))
            elif hasattr(part, 'content'):
                texts.append(str(part.content))
        
        return '\n'.join(texts)
    
    async def stream_response(self, session_id: str, message: str) -> AsyncIterator[str]:
        """
        Stream response from agent.
        
        Args:
            session_id: Session ID from create_session
            message: User message to send
            
        Yields:
            Response text chunks
        """
        if session_id not in self._sessions:
            raise OpenCodeError(f"Session {session_id} not found")
        
        session_data = self._sessions[session_id]
        
        try:
            client = await self._get_client()
            
            # Build message parts
            parts: List[Dict[str, Any]] = [
                {"type": "text", "text": message}
            ]
            
            # Enable all MCP tools
            tools: Dict[str, bool] = {"*": True}
            
            # Use streaming response with mode parameter
            # max_tokens is configured in opencode.json model options
            async with client.session.with_streaming_response.chat(
                session_id,
                model_id=self.model_id,
                provider_id=self.provider_id,
                parts=parts,
                mode=session_data["agent"],  # Specify agent mode from opencode.json
                system=session_data["system_prompt"],  # Fallback system prompt
                tools=tools,
            ) as response:
                async for chunk in response.iter_text():
                    if chunk:
                        yield chunk
                        
        except OpenCodeError:
            raise
        except Exception as e:
            server_url = self.base_url or "default"
            logger.error(f"Failed to stream response for session {session_id}: {e}")
            raise OpenCodeError(
                f"Failed to stream response (is OpenCode server running at {server_url}?): {e}"
            )
    
    async def close_session(self, session_id: str):
        """
        Close a session.
        
        Args:
            session_id: Session ID to close
        """
        if session_id in self._sessions:
            try:
                client = await self._get_client()
                await client.session.delete(session_id)
            except Exception as e:
                logger.warning(f"Error deleting session {session_id}: {e}")
            finally:
                del self._sessions[session_id]
                logger.info(f"Closed session {session_id}")
    
    async def close(self):
        """Close the client and all sessions"""
        # Close all sessions
        session_ids = list(self._sessions.keys())
        for session_id in session_ids:
            await self.close_session(session_id)
        
        # Close the client
        await self._close_client()
